name: Deploy Docsify

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone content repository
        run: |
          git clone https://github.com/cassiocostawk/Estudo.git content
          cp -r content/* docs/

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Docsify CLI
        run: npm install -g docsify-cli

      - name: Build Docsify site
        run: docsify init ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs